[package]
name = "eq-sat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egg = "0.9.5"
expr-utils = { path = "./expr-utils" }

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
